name: Jest Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Run Server and Tests
        run: npm start /server/server.js & npm test /server/server.test.js
